# yamllint disable-line rule:document-start
name: Run Checks

on: [push, pull_request]

jobs:
  pre-commit-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 3
    - name: Install dependencies
      run: |
        sudo apt-get update
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --all-files --verbose